import React from 'react';
import { Link } from 'react-router-dom';
import { Mic, Brain, BarChart3, Users, Clock, Target } from 'lucide-react';

const Home = () => {
  const features = [
    {
      icon: <Brain size={24} />,
      title: "AI-Powered Questions",
      description: "Get personalized interview questions generated by advanced AI based on your role and experience level."
    },
    {
      icon: <Mic size={24} />,
      title: "Voice Recognition",
      description: "Practice with real-time speech recognition technology that captures and analyzes your responses."
    },
    {
      icon: <BarChart3 size={24} />,
      title: "Detailed Analytics",
      description: "Receive comprehensive feedback on your performance with scoring and improvement suggestions."
    },
    {
      icon: <Users size={24} />,
      title: "Multiple Roles",
      description: "Practice for various positions including Software Engineer, Data Scientist, Product Manager, and more."
    },
    {
      icon: <Clock size={24} />,
      title: "Flexible Duration",
      description: "Choose interview lengths from quick 15-minute sessions to comprehensive 60-minute interviews."
    },
    {
      icon: <Target size={24} />,
      title: "Skill Assessment",
      description: "Get evaluated on technical knowledge, communication skills, and overall interview readiness."
    }
  ];

  return (
    <div>
      <section className="hero-section">
        <div className="container">
          <h1>Master Your Next Interview</h1>
          <p>
            Practice with AI-powered mock interviews tailored to your dream job. 
            Get real-time feedback and improve your interview skills with confidence.
          </p>
          <Link to="/setup" className="btn btn-primary" style={{ fontSize: '1.1rem', padding: '16px 32px' }}>
            Start Your Interview Practice
          </Link>
        </div>
      </section>

      <section style={{ padding: '80px 0', backgroundColor: 'rgba(255, 255, 255, 0.1)' }}>
        <div className="container">
          <h2 style={{ 
            textAlign: 'center', 
            marginBottom: '60px', 
            color: 'white',
            fontSize: '2.5rem',
            fontWeight: '600'
          }}>
            Why Choose Our AI Interview Simulator?
          </h2>
          
          <div className="features-grid">
            {features.map((feature, index) => (
              <div key={index} className="feature-card">
                <div className="feature-icon">
                  {feature.icon}
                </div>
                <h3 style={{ marginBottom: '16px', fontSize: '1.3rem', fontWeight: '600' }}>
                  {feature.title}
                </h3>
                <p style={{ color: '#6c757d', lineHeight: '1.6' }}>
                  {feature.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section style={{ padding: '80px 0' }}>
        <div className="container" style={{ textAlign: 'center' }}>
          <h2 style={{ 
            marginBottom: '24px', 
            color: 'white',
            fontSize: '2.5rem',
            fontWeight: '600'
          }}>
            Ready to Ace Your Interview?
          </h2>
          <p style={{ 
            marginBottom: '40px', 
            color: 'rgba(255, 255, 255, 0.9)',
            fontSize: '1.1rem',
            maxWidth: '600px',
            margin: '0 auto 40px'
          }}>
            Join thousands of job seekers who have improved their interview skills 
            and landed their dream jobs using our AI-powered platform.
          </p>
          <Link 
            to="/setup" 
            className="btn btn-primary" 
            style={{ 
              fontSize: '1.1rem', 
              padding: '16px 32px',
              marginRight: '16px'
            }}
          >
            Get Started Now
          </Link>
          <Link 
            to="/dashboard" 
            className="btn btn-secondary"
            style={{ 
              fontSize: '1.1rem', 
              padding: '16px 32px'
            }}
          >
            View Dashboard
          </Link>
        </div>
      </section>
    </div>
  );
};

export default Home;
